startCategory(cfin(_)).
[acht] :: [c1,-b].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot)]
[acht] :: [c1,-b,-a,-d].
[acht] :: [c1].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[acht] :: [c2b].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[acht] :: [cfin].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[acht] :: [c3e].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[drei] :: [c1,-c].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,+b,+a,c1,-c],dot)]
[drei] :: [c1,-c,-b,-a].
[drei] :: [c1].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot),epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot)]
[drei] :: [cfin].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[drei] :: [c3e].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[eins] :: [c1].
[eins] :: [cfin].%[eins] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[eins] :: [c3e].%[eins] :: [c1], [epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[einund] :: [=c21s,cfin].%[einund] :: [=c21s,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einund] :: [=c23s,cfin].%[einund] :: [=c23s,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einundsechzig] :: [c3e].%[einundsechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[einundsiebzig] :: [c3e].%[einundsiebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[einundzwanzig] :: [c3e].%[einundzwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[elf] :: [c3e].%[elf] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[fünf] :: [c1,-b].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot)]
[fünf] :: [c1,-b,-a,-d].
[fünf] :: [c1].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[fünf] :: [c2b].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[fünf] :: [cfin].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[fünf] :: [c3e].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[hundert] :: [cfin].%[hundert] :: [c3], [epsLi([=c3,cfin],dot)]
[hundert] :: [=c1,+b,cfin].%[hundert] :: [=c1,+b,c3], [epsLi([=c3,cfin],dot)]
[hundert] :: [=c3e,cfin].%[hundert] :: [=c3e,c3], [epsLi([=c3,cfin],dot)]
[hundert] :: [=c3e,=c2b,cfin].%[hundert] :: [=c3e,=c2b,c3], [epsLi([=c3,cfin],dot)]
[neun] :: [c1,-b].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot)]
[neun] :: [c1,-b,-a,-d].
[neun] :: [c1].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[neun] :: [c2b].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[neun] :: [cfin].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[neun] :: [c3e].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sechs] :: [c1].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot)]
[sechs] :: [c2b].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c2b],dot)]
[sechs] :: [c1,-b].
[sechs] :: [c3e].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sechs] :: [cfin].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[sechzehn] :: [c3e].%[sechzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sechzig] :: [c3e].%[sechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sieben] :: [c1].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot)]
[sieben] :: [c2b].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c2b],dot)]
[sieben] :: [c1,-b].
[sieben] :: [c3e].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sieben] :: [cfin].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[siebzehn] :: [c3e].%[siebzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[siebzig] :: [c3e].%[siebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[und] :: [=c22s,=c2b,cfin].%[und] :: [=c22s,=c2b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[und] :: [=c24s,=c2b,cfin].%[und] :: [=c24s,=c2b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[undsechzig] :: [=c1,+b,cfin].%[undsechzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[undsiebzig] :: [=c1,+b,cfin].%[undsiebzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[undzwanzig] :: [=c1,+b,cfin].%[undzwanzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[vier] :: [c1,-b].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot)]
[vier] :: [c1,-d].
[vier] :: [c1,-b,-a,-d].
[vier] :: [c1].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[vier] :: [c2b].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[vier] :: [cfin].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[vier] :: [c3e].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[zehn] :: [c3e].%[zehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[zehn] :: [=c1,+a,cfin].%[zehn] :: [=c1,+a,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zig] :: [=c1,+d,cfin].%[zig] :: [=c1,+d,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zig] :: [=c1,+d,c23s].
[zig] :: [=c1,+d,c24s].
[zig] :: [=c1,+d,c3e].
[zwanzig] :: [c3e].%[zwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[zwei] :: [c1].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot)]
[zwei] :: [c2b].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c2b],dot)]
[zwei] :: [c1,-b].
[zwei] :: [c3e].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[zwei] :: [cfin].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[zwölf] :: [c3e].%[zwölf] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[ßig] :: [=c1,+c,cfin].%[ßig] :: [=c1,+c,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[ßig] :: [=c1,+c,c21s].
[ßig] :: [=c1,+c,c22s].
[acht] :: [c1,-a].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot)]
[drei] :: [c2b].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[drei] :: [c1,-b].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot)]
[einundsechzig] :: [cfin].%[einundsechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einundsiebzig] :: [cfin].%[einundsiebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einundzwanzig] :: [cfin].%[einundzwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[elf] :: [cfin].%[elf] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[fünf] :: [c1,-a].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot)]
[neun] :: [c1,-a].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot)]
[sechzehn] :: [cfin].%[sechzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[sechzig] :: [cfin].%[sechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[siebzehn] :: [cfin].%[siebzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[siebzig] :: [cfin].%[siebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[vier] :: [c1,-a].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot)]
[zehn] :: [cfin].%[zehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zwanzig] :: [cfin].%[zwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zwölf] :: [cfin].%[zwölf] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
