startCategory(cfin).
[drei] :: ([c1,-c,-a,-b]).
[zehn] :: ([c2,-f0,-s1]).
[elf] :: ([c2,-f0,-s1]).
[zwölf] :: ([c2,-f0,-s1]).
[zehn] :: ([=c1,+a,c2,-f0,-s1]).
[sechzehn] :: ([c2,-f0,-s1]).
[siebzehn] :: ([c2,-f0,-s1]).
[zwanzig] :: ([c2,-f0,-s1]).
[einundzwanzig] :: ([c2,-f0,-s1]).
[undzwanzig] :: ([=c1,+b,c2,-f0,-s1]).
[ßig] :: ([=c1,+c,c2,-f0,-s1]).
[einund] :: ([=c21s,c2,-f0,-s1]).
[ßig] :: ([=c1,+c,c21s]).
[und] :: ([=c22s,=c2b,c2,-f0,-s1]).
[ßig] :: ([=c1,+c,c22s]).
[zig] :: ([=c1,+d,c2,-f0,-s1]).
[einund] :: ([=c23s,c2,-f0,-s1]).
[zig] :: ([=c1,+d,c23s]).
[und] :: ([=c24s,=c2b,c2,-f0,-s1]).
[zig] :: ([=c1,+d,c24s]).
[sechzig] :: ([c2,-f0,-s1]).
[einundsechzig] :: ([c2,-f0,-s1]).
[undsechzig] :: ([=c1,+b,c2,-f0,-s1]).
[siebzig] :: ([c2,-f0,-s1]).
[einundsiebzig] :: ([c2,-f0,-s1]).
[undsiebzig] :: ([=c1,+b,c2,-f0,-s1]).
[eins] :: ([c1]).
[zwei] :: ([c1,-b]).
[vier] :: ([c1,-a,-b,-d]).
[fünf] :: ([c1,-a,-b,-d]).
[sechs] :: ([c1,-b]).
[sieben] :: ([c1,-b]).
[acht] :: ([c1,-a,-b,-d]).
[neun] :: ([c1,-a,-b,-d]).
[einhundert] :: ([c3,-s0]).
[einhundert] :: ([=c2,c3,-s0]).
[hundert] :: ([=c1,+b,c3,-s0]).
[hundert] :: ([=c2,=c2b,c3,-s0]).
[eintausend] :: ([c4]).
[eintausend] :: ([=c3,c4]).
[tausend] :: ([=c1,+b,c4]).
[tausend] :: ([=c3,=c2b,c4]).
[] :: ([=c4,cfin]).
[] :: ([=c1,+b,c2b]).
[] :: ([=c1,c2]).
[] :: ([=c2,+f0,c3]).
[] :: ([=c1,c3]).
[] :: ([=c3,+s0,c4]).
[] :: ([=c2,+s1,c4]).
[] :: ([=c1,c4]).
[] :: ([=c1,+a,c1]).
[] :: ([=c2,+s1,c2]).
[] :: ([=c1,+d,c1]).
[] :: ([=c3,+s0,c3]).
[] :: ([=c1,+c,c1]).
[] :: ([=c1,+b,c1]).
[] :: ([=c2,+f0,c2]).
[] :: ([=c1,+c,+a,+b,c1,-c]).
[] :: ([=c2,+f0,+s1,c2,-f0]).
[] :: ([=c1,+a,+b,+d,c1,-a]).
[] :: ([=c1,+b,+d,c1,-b]).
[] :: ([=c1,+a,+b,c1,-a]).
