startCategory(cfin).
[y_] :: [=c1,=c2b,c3].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y_] :: [=c1,=c2b,c2,-f0].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[y] :: [=c1,+b,c3].%[y] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[y] :: [=c1,+b,c2].%[y] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[y] :: [=c1,+b,c2,-f0].%[y] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[ty_] :: [=c1,=c2d,c3].%[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[ty_] :: [=c1,=c2d,c2].%[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[ty_] :: [=c1,=c2d,c2,-f0].%[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[ty] :: [=c1,+d,c3].%[ty] :: [=c1,+d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[ty] :: [=c1,+d,c2].%[ty] :: [=c1,+d,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[ty] :: [=c1,+d,c2,-f0].%[ty] :: [=c1,+d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[twenty_] :: [=c1,c3].%[twenty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[twenty_] :: [=c1,c2].%[twenty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[twenty_] :: [=c1,c2,-f0].%[twenty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[twenty] :: [c3].%[twenty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[twenty] :: [c2].%[twenty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[twenty] :: [c2,-f0].%[twenty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[twelve] :: [c3].%[twelve] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[twelve] :: [c2].%[twelve] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[twelve] :: [c2,-f0].%[twelve] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[thirty_] :: [=c1,c3].%[thirty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[thirty_] :: [=c1,c2].%[thirty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[thirty_] :: [=c1,c2,-f0].%[thirty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[thirty] :: [c3].%[thirty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[thirty] :: [c2].%[thirty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[thirty] :: [c2,-f0].%[thirty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[thirteen] :: [c3].%[thirteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[thirteen] :: [c2].%[thirteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[thirteen] :: [c2,-f0].%[thirteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[ten] :: [c3].%[ten] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[ten] :: [c2].%[ten] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[ten] :: [c2,-f0].%[ten] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[teen] :: [=c1,+a,c3].%[teen] :: [=c1,+a,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[teen] :: [=c1,+a,c2].%[teen] :: [=c1,+a,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[teen] :: [=c1,+a,c2,-f0].%[teen] :: [=c1,+a,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[six] :: [c1].%[six] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot)]
[six] :: [c1,-a].%[six] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot)]
[six] :: [c4].%[six] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c4],dot)]
[six] :: [c3].%[six] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c3],dot)]
[six] :: [c2].%[six] :: [c1,-ds,-a], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+gs,c2],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2],dot)]
[six] :: [c2,-gs].%[six] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot)]
[six] :: [cfin].%[six] :: [c1,-ds,-a], [epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[six] :: [c2,-g].%[six] :: [c1,-ds,-a], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot)]
[six] :: [c4g].%[six] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[seven] :: [c1].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot)]
[seven] :: [c1,-a].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot)]
[seven] :: [c4].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c4],dot)]
[seven] :: [c3].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c3],dot)]
[seven] :: [c2].%[seven] :: [c1,-ds,-a], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+gs,c2],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2],dot)]
[seven] :: [c2,-gs].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot)]
[seven] :: [cfin].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[seven] :: [c2,-g].%[seven] :: [c1,-ds,-a], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot)]
[seven] :: [c4g].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[nine] :: [c1].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot)]
[nine] :: [c1,-a].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot)]
[nine] :: [c4].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c4],dot)]
[nine] :: [c3].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c3],dot)]
[nine] :: [c2].%[nine] :: [c1,-ds,-a], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+gs,c2],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2],dot)]
[nine] :: [c2,-gs].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot)]
[nine] :: [cfin].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[nine] :: [c2,-g].%[nine] :: [c1,-ds,-a], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot)]
[nine] :: [c4g].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+ds,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[hundred_and] :: [=c2,=c1,c4h].%[hundred_and] :: [=c2,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,c3],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c4h],dot)]
[hundred_and] :: [=c2,=c1,c3].%[hundred_and] :: [=c2,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,c3],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3],dot)]
[hundred_and] :: [=c2,=c1,c3,-h].%[hundred_and] :: [=c2,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,c3],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot)]
[hundred] :: [=cnix,=c1,c4h].%[hundred] :: [=cnix,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,c3],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c4h],dot)]
[hundred] :: [=cnix,=c1,c3].%[hundred] :: [=cnix,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,c3],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3],dot)]
[hundred] :: [=cnix,=c1,c3,-h].%[hundred] :: [=cnix,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,c3],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot),epsLi([=c3,+h,c3,-h],dot)]
[forty_] :: [=c1,c3].%[forty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[forty_] :: [=c1,c2].%[forty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[forty_] :: [=c1,c2,-f0].%[forty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[forty] :: [c3].%[forty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[forty] :: [c2].%[forty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[forty] :: [c2,-f0].%[forty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[fifty_] :: [=c1,c3].%[fifty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[fifty_] :: [=c1,c2].%[fifty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[fifty_] :: [=c1,c2,-f0].%[fifty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[fifty] :: [c3].%[fifty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[fifty] :: [c2].%[fifty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[fifty] :: [c2,-f0].%[fifty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[fifteen] :: [c3].%[fifteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[fifteen] :: [c2].%[fifteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[fifteen] :: [c2,-f0].%[fifteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[eleven] :: [c3].%[eleven] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[eleven] :: [c2].%[eleven] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[eleven] :: [c2,-f0].%[eleven] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[een] :: [=c1,+b,c3].%[een] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c3],dot)]
[een] :: [=c1,+b,c2].%[een] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+g,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot),epsLi([=c2,+f0,c2],dot)]
[een] :: [=c1,+b,c2,-f0].%[een] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,+g,c2,-f0],dot)]
[y_] :: [=c1,=c2b,cfin].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[y_] :: [=c1,=c2b,c4].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[y_] :: [=c1,=c2b,c2,-s0].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g].
[y] :: [=c1,+b,cfin].%[y] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[y] :: [=c1,+b,c4].%[y] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[y] :: [=c1,+b,c2,-s0].%[y] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[y] :: [=c1,+b,c2,-s0s,-f0,-g].
[ty_] :: [=c1,=c2d,cfin].%[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[ty_] :: [=c1,=c2d,c4].%[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[ty_] :: [=c1,=c2d,c2,-s0].%[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g].
[ty] :: [=c1,+d,cfin].%[ty] :: [=c1,+d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[ty] :: [=c1,+d,c4].%[ty] :: [=c1,+d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[ty] :: [=c1,+d,c2,-s0].%[ty] :: [=c1,+d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[ty] :: [=c1,+d,c2,-s0s,-f0,-g].
[two] :: [c4g].%[two] :: [c1], [epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[two] :: [cfin].%[two] :: [c1], [epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[two] :: [c2].%[two] :: [c1], [epsLi([=c2,+gs,c2],dot),epsLi([=c1,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2],dot)]
[two] :: [c2,-g].%[two] :: [c1], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[two] :: [c4].%[two] :: [c1], [epsLi([=c1,c4],dot)]
[two] :: [c3].%[two] :: [c1], [epsLi([=c1,c3],dot)]
[two] :: [c2,-gs].%[two] :: [c1], [epsLi([=c1,c2,-gs],dot)]
[two] :: [c1].
[twenty_] :: [=c1,cfin].%[twenty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[twenty_] :: [=c1,c4].%[twenty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[twenty_] :: [=c1,c2,-s0].%[twenty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[twenty_] :: [=c1,c2,-s0s,-f0,-g].
[twenty] :: [cfin].%[twenty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[twenty] :: [c4].%[twenty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[twenty] :: [c2,-s0].%[twenty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[twenty] :: [c2,-s0s,-f0,-g].
[twelve] :: [cfin].%[twelve] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[twelve] :: [c4].%[twelve] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[twelve] :: [c2,-s0].%[twelve] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[twelve] :: [c2,-s0s,-f0,-g].
[three] :: [c4g].%[three] :: [c1], [epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[three] :: [cfin].%[three] :: [c1], [epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[three] :: [c2].%[three] :: [c1], [epsLi([=c2,+gs,c2],dot),epsLi([=c1,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2],dot)]
[three] :: [c2,-g].%[three] :: [c1], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[three] :: [c4].%[three] :: [c1], [epsLi([=c1,c4],dot)]
[three] :: [c3].%[three] :: [c1], [epsLi([=c1,c3],dot)]
[three] :: [c2,-gs].%[three] :: [c1], [epsLi([=c1,c2,-gs],dot)]
[three] :: [c1].
[thousand_k] :: [=c4h,=c3,cfin].%[thousand_k] :: [=c4h,=c3,c4], [epsLi([=c4,cfin],dot)]
[thousand_k] :: [=c4h,=c3,c4].
[thousand_and] :: [=c4g,=c3,cfin].%[thousand_and] :: [=c4g,=c3,c4], [epsLi([=c4,cfin],dot)]
[thousand_and] :: [=c4g,=c3,c4].
[thousand] :: [=cnix,=c3,cfin].%[thousand] :: [=cnix,=c3,c4], [epsLi([=c4,cfin],dot)]
[thousand] :: [=cnix,=c3,c4].
[thirty_] :: [=c1,cfin].%[thirty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[thirty_] :: [=c1,c4].%[thirty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[thirty_] :: [=c1,c2,-s0].%[thirty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[thirty_] :: [=c1,c2,-s0s,-f0,-g].
[thirty] :: [cfin].%[thirty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[thirty] :: [c4].%[thirty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[thirty] :: [c2,-s0].%[thirty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[thirty] :: [c2,-s0s,-f0,-g].
[thirteen] :: [cfin].%[thirteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[thirteen] :: [c4].%[thirteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[thirteen] :: [c2,-s0].%[thirteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[thirteen] :: [c2,-s0s,-f0,-g].
[ten] :: [cfin].%[ten] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[ten] :: [c4].%[ten] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[ten] :: [c2,-s0].%[ten] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[ten] :: [c2,-s0s,-f0,-g].
[teen] :: [=c1,+a,cfin].%[teen] :: [=c1,+a,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[teen] :: [=c1,+a,c4].%[teen] :: [=c1,+a,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[teen] :: [=c1,+a,c2,-s0].%[teen] :: [=c1,+a,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[teen] :: [=c1,+a,c2,-s0s,-f0,-g].
[six] :: [c2d].%[six] :: [c1,-ds,-a], [epsLi([=c1,+ds,+a,c1,-d],dot),epsLi([=c1,+d,c2d],dot)]
[six] :: [c1,-d].%[six] :: [c1,-ds,-a], [epsLi([=c1,+ds,+a,c1,-d],dot)]
[six] :: [c1,-ds,-a].
[seven] :: [c2d].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+ds,+a,c1,-d],dot),epsLi([=c1,+d,c2d],dot)]
[seven] :: [c1,-d].%[seven] :: [c1,-ds,-a], [epsLi([=c1,+ds,+a,c1,-d],dot)]
[seven] :: [c1,-ds,-a].
[one] :: [c4g].%[one] :: [c1], [epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[one] :: [cfin].%[one] :: [c1], [epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[one] :: [c2].%[one] :: [c1], [epsLi([=c2,+gs,c2],dot),epsLi([=c1,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2],dot)]
[one] :: [c2,-g].%[one] :: [c1], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[one] :: [c4].%[one] :: [c1], [epsLi([=c1,c4],dot)]
[one] :: [c3].%[one] :: [c1], [epsLi([=c1,c3],dot)]
[one] :: [c2,-gs].%[one] :: [c1], [epsLi([=c1,c2,-gs],dot)]
[one] :: [c1].
[nine] :: [c2d].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+ds,+a,c1,-d],dot),epsLi([=c1,+d,c2d],dot)]
[nine] :: [c1,-d].%[nine] :: [c1,-ds,-a], [epsLi([=c1,+ds,+a,c1,-d],dot)]
[nine] :: [c1,-ds,-a].
[hundred_and] :: [=c2,=c1,cfin].%[hundred_and] :: [=c2,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,+h,c3,-s1],dot),epsLi([=c3,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[hundred_and] :: [=c2,=c1,c4].%[hundred_and] :: [=c2,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,+h,c3,-s1],dot),epsLi([=c3,+s1,c4],dot)]
[hundred_and] :: [=c2,=c1,c3,-s1].%[hundred_and] :: [=c2,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,+h,c3,-s1],dot)]
[hundred_and] :: [=c2,=c1,c3,-s1s,-h].
[hundred] :: [=cnix,=c1,cfin].%[hundred] :: [=cnix,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,+h,c3,-s1],dot),epsLi([=c3,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[hundred] :: [=cnix,=c1,c4].%[hundred] :: [=cnix,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,+h,c3,-s1],dot),epsLi([=c3,+s1,c4],dot)]
[hundred] :: [=cnix,=c1,c3,-s1].%[hundred] :: [=cnix,=c1,c3,-s1s,-h], [epsLi([=c3,+s1s,+h,c3,-s1],dot)]
[hundred] :: [=cnix,=c1,c3,-s1s,-h].
[four] :: [c4g].%[four] :: [c1,-as0], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+as0,c1,-a],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+as0,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[four] :: [c2].%[four] :: [c1,-as0], [epsLi([=c1,c2],dot),epsLi([=c2,+gs,c2],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+as0,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+as0,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2],dot)]
[four] :: [c2,-g].%[four] :: [c1,-as0], [epsLi([=c1,+a,c1,-a],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+as0,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+as0,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[four] :: [cfin].%[four] :: [c1,-as0], [epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+as0,c1,-a],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+as0,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[four] :: [c2,-gs].%[four] :: [c1,-as0], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+as0,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+as0,c1],dot),epsLi([=c1,c2,-gs],dot)]
[four] :: [c3].%[four] :: [c1,-as0], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+as0,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+as0,c1],dot),epsLi([=c1,c3],dot)]
[four] :: [c4].%[four] :: [c1,-as0], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+as0,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+as0,c1],dot),epsLi([=c1,c4],dot)]
[four] :: [c1].%[four] :: [c1,-as0], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+as0,c1,-a],dot),epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+as0,c1],dot)]
[four] :: [c1,-a].%[four] :: [c1,-as0], [epsLi([=c1,+a,c1,-a],dot),epsLi([=c1,+as0,c1,-a],dot)]
[four] :: [c1,-as0].
[forty_] :: [=c1,cfin].%[forty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[forty_] :: [=c1,c4].%[forty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[forty_] :: [=c1,c2,-s0].%[forty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[forty_] :: [=c1,c2,-s0s,-f0,-g].
[forty] :: [cfin].%[forty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[forty] :: [c4].%[forty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[forty] :: [c2,-s0].%[forty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[forty] :: [c2,-s0s,-f0,-g].
[five] :: [c4g].%[five] :: [c1], [epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[five] :: [cfin].%[five] :: [c1], [epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[five] :: [c2].%[five] :: [c1], [epsLi([=c2,+gs,c2],dot),epsLi([=c1,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2],dot)]
[five] :: [c2,-g].%[five] :: [c1], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[five] :: [c4].%[five] :: [c1], [epsLi([=c1,c4],dot)]
[five] :: [c3].%[five] :: [c1], [epsLi([=c1,c3],dot)]
[five] :: [c2,-gs].%[five] :: [c1], [epsLi([=c1,c2,-gs],dot)]
[five] :: [c1].
[fifty_] :: [=c1,cfin].%[fifty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[fifty_] :: [=c1,c4].%[fifty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[fifty_] :: [=c1,c2,-s0].%[fifty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[fifty_] :: [=c1,c2,-s0s,-f0,-g].
[fifty] :: [cfin].%[fifty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[fifty] :: [c4].%[fifty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[fifty] :: [c2,-s0].%[fifty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[fifty] :: [c2,-s0s,-f0,-g].
[fifteen] :: [cfin].%[fifteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[fifteen] :: [c4].%[fifteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[fifteen] :: [c2,-s0].%[fifteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[fifteen] :: [c2,-s0s,-f0,-g].
[eleven] :: [cfin].%[eleven] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[eleven] :: [c4].%[eleven] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[eleven] :: [c2,-s0].%[eleven] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[eleven] :: [c2,-s0s,-f0,-g].
[eight] :: [c4g].%[eight] :: [c1,-bs], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+bs,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[eight] :: [c2].%[eight] :: [c1,-bs], [epsLi([=c1,c2],dot),epsLi([=c2,+gs,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+bs,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2],dot)]
[eight] :: [c2,-g].%[eight] :: [c1,-bs], [epsLi([=c2,+g,c2,-g],dot),epsLi([=c1,+bs,c1],dot),epsLi([=c1,c2,-gs],dot),epsLi([=c2,+gs,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[eight] :: [cfin].%[eight] :: [c1,-bs], [epsLi([=c1,+bs,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[eight] :: [c2,-gs].%[eight] :: [c1,-bs], [epsLi([=c1,+bs,c1],dot),epsLi([=c1,c2,-gs],dot)]
[eight] :: [c3].%[eight] :: [c1,-bs], [epsLi([=c1,+bs,c1],dot),epsLi([=c1,c3],dot)]
[eight] :: [c4].%[eight] :: [c1,-bs], [epsLi([=c1,+bs,c1],dot),epsLi([=c1,c4],dot)]
[eight] :: [c2b].%[eight] :: [c1,-bs], [epsLi([=c1,+bs,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[eight] :: [c1].%[eight] :: [c1,-bs], [epsLi([=c1,+bs,c1],dot)]
[eight] :: [c1,-b].%[eight] :: [c1,-bs], [epsLi([=c1,+bs,c1,-b],dot)]
[eight] :: [c1,-bs].
[een] :: [=c1,+b,cfin].%[een] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot),epsLi([=c4,cfin],dot)]
[een] :: [=c1,+b,c4].%[een] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot),epsLi([=c2,+s0,c4],dot)]
[een] :: [=c1,+b,c2,-s0].%[een] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,+f0,+g,c2,-s0],dot)]
[een] :: [=c1,+b,c2,-s0s,-f0,-g].
[een] :: [=c1,+b,c4g].%[een] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[een] :: [=c1,+b,c2,-g].%[een] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[eleven] :: [c4g].%[eleven] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[eleven] :: [c2,-g].%[eleven] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[fifteen] :: [c4g].%[fifteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[fifteen] :: [c2,-g].%[fifteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[fifty] :: [c4g].%[fifty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[fifty] :: [c2,-g].%[fifty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[fifty_] :: [=c1,c4g].%[fifty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[fifty_] :: [=c1,c2,-g].%[fifty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[forty] :: [c4g].%[forty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[forty] :: [c2,-g].%[forty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[forty_] :: [=c1,c4g].%[forty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[forty_] :: [=c1,c2,-g].%[forty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[teen] :: [=c1,+a,c4g].%[teen] :: [=c1,+a,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[teen] :: [=c1,+a,c2,-g].%[teen] :: [=c1,+a,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[ten] :: [c4g].%[ten] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[ten] :: [c2,-g].%[ten] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[thirteen] :: [c4g].%[thirteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[thirteen] :: [c2,-g].%[thirteen] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[thirty] :: [c4g].%[thirty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[thirty] :: [c2,-g].%[thirty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[thirty_] :: [=c1,c4g].%[thirty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[thirty_] :: [=c1,c2,-g].%[thirty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[twelve] :: [c4g].%[twelve] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[twelve] :: [c2,-g].%[twelve] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[twenty] :: [c4g].%[twenty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[twenty] :: [c2,-g].%[twenty] :: [c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[twenty_] :: [=c1,c4g].%[twenty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[twenty_] :: [=c1,c2,-g].%[twenty_] :: [=c1,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[ty] :: [=c1,+d,c4g].%[ty] :: [=c1,+d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[ty] :: [=c1,+d,c2,-g].%[ty] :: [=c1,+d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[ty_] :: [=c1,=c2d,c4g].%[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[ty_] :: [=c1,=c2d,c2,-g].%[ty_] :: [=c1,=c2d,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[y] :: [=c1,+b,c4g].%[y] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[y] :: [=c1,+b,c2,-g].%[y] :: [=c1,+b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[y_] :: [=c1,=c2b,c4g].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c4g],dot)]
[y_] :: [=c1,=c2b,c2,-g].%[y_] :: [=c1,=c2b,c2,-s0s,-f0,-g], [epsLi([=c2,+s0s,c2],dot),epsLi([=c2,+f0,c2],dot),epsLi([=c2,+g,c2,-g],dot),epsLi([=c2,+g,c2,-g],dot)]
[] :: [cnix].
