startCategory(cfin).
[treize] :: [c3e].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[treize] :: [c2,-e].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot)]
[quinze] :: [c3e].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[quinze] :: [c2,-e].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot)]
[quatorze] :: [c3e].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[quatorze] :: [c2,-e].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot)]
[onze] :: [c4m].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[onze] :: [c3,-m].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[onze] :: [c3,-ms].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[onze] :: [c2].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+m1s,c2],dot),epsLi([=c2,+h,+m1s,c2,-h],dot),epsLi([=c2,+j1,+f,+h,+m1s,c2,-j1],dot),epsLi([=c2,+s1,+j1,+f,+h,+m1s,c2,-s1],dot),epsLi([=c2,+f,+h,+m1s,c2,-f],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+m1,c2],dot)]
[onze] :: [c2,-m1].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot)]
[onze] :: [c3].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c2,+j1,+f,+h,+m1s,c2,-j1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[douze] :: [c3e].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[douze] :: [c2,-e].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot)]
[vingts] :: [=c1,+g,c4m].%[vingts] :: [=c1,+g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[vingts] :: [=c1,+g,c3,-m].%[vingts] :: [=c1,+g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[vingt_et] :: [=c3b,c4m].%[vingt_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[vingt_et] :: [=c3b,c3,-m].%[vingt_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[vingt] :: [=c3h,=c3g,c4m].%[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[vingt] :: [=c3h,=c3g,c3,-m].%[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[vingt] :: [=c3c,c4m].%[vingt] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[vingt] :: [=c3c,c3,-m].%[vingt] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[vingt] :: [c4j].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1s,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[vingt] :: [c3].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c3,+ms,c3],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c3,+js,c3],dot),epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1s,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c3],dot)]
[vingt] :: [c3,-j].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1s,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[vingt] :: [c2].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+m1s,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+s1,+j1,+m1s,c2,-s1],dot),epsLi([=c2,+i,+s1,+j1,+m1s,c2,-i],dot),epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1s,c2,-j1],dot),epsLi([=c2,+j1,c2],dot)]
[vingt] :: [c3,-js].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1s,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[vingt] :: [c2,-j1].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1s,c2,-j1],dot)]
[uante_et] :: [=c3b,=c3d,c4m].%[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[uante_et] :: [=c3b,=c3d,c3,-m].%[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[uante] :: [=c3c,=c3d,c4m].%[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[uante] :: [=c3c,=c3d,c3,-m].%[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[uante] :: [=c1,+d,c4m].%[uante] :: [=c1,+d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[uante] :: [=c1,+d,c3,-m].%[uante] :: [=c1,+d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[trente_et] :: [=c3b,c4m].%[trente_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[trente_et] :: [=c3b,c3,-m].%[trente_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[trente] :: [=c3c,c4m].%[trente] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[trente] :: [=c3c,c3,-m].%[trente] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[trente] :: [c4m].%[trente] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[trente] :: [c3,-m].%[trente] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[treize] :: [c3h].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[treize] :: [c2].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+es,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot),epsLi([=c2,+h,c2],dot)]
[treize] :: [c2,-h].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot)]
[soixante_et] :: [=c3f,c4m].%[soixante_et] :: [=c3f,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[soixante_et] :: [=c3f,c3,-m].%[soixante_et] :: [=c3f,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[soixante] :: [=c3e,c4m].%[soixante] :: [=c3e,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[soixante] :: [=c3e,c3,-m].%[soixante] :: [=c3e,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[soixante] :: [c4m].%[soixante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[soixante] :: [c3,-m].%[soixante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[sept] :: [c3e].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sept] :: [c2,-e].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot)]
[sept] :: [c2,-es].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot)]
[sept] :: [c1,-e0].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot)]
[sept] :: [c2].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+hs,c2],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2],dot)]
[seize] :: [c4m].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[seize] :: [c3,-m].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[seize] :: [c3,-ms].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[seize] :: [c2].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+es,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c2],dot)]
[seize] :: [c2,-m1].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot)]
[seize] :: [c3].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[quinze] :: [c3h].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[quinze] :: [c2].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+es,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot),epsLi([=c2,+h,c2],dot)]
[quinze] :: [c2,-h].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot)]
[quatre] :: [c3e].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+g,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[quatre] :: [c2,-e].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+g,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot)]
[quatre] :: [c2,-es].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+g,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot)]
[quatre] :: [c1,-e0].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+g,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot)]
[quatre] :: [c2].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+hs,c2],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2],dot)]
[quatorze] :: [c3h].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[quatorze] :: [c2].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+es,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot),epsLi([=c2,+h,c2],dot)]
[quatorze] :: [c2,-h].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot)]
[quarante_et] :: [=c3b,c4m].%[quarante_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[quarante_et] :: [=c3b,c3,-m].%[quarante_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[quarante_] :: [=c3c,c4m].%[quarante_] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[quarante_] :: [=c3c,c3,-m].%[quarante_] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[quarante] :: [c4m].%[quarante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[quarante] :: [c3,-m].%[quarante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+ms,c3,-m],dot)]
[onze] :: [c3f].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,+h,+m1s,c2,-f],dot),epsLi([=c2,+f,c3f],dot)]
[onze] :: [c2,-f].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,+h,+m1s,c2,-f],dot)]
[neuf] :: [c3e].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[neuf] :: [c2,-e].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot)]
[neuf] :: [c2,-es].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot)]
[neuf] :: [c1,-e0].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot)]
[neuf] :: [c2].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+hs,c2],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2],dot)]
[huit] :: [c3e].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[huit] :: [c2,-e].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot)]
[huit] :: [c2,-es].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot)]
[huit] :: [c1,-e0].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot)]
[huit] :: [c2].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+hs,c2],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2],dot)]
[douze] :: [c3h].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[douze] :: [c2].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+es,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot),epsLi([=c2,+h,c2],dot)]
[douze] :: [c2,-h].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,+m1,+es,c2,-h],dot)]
[dix] :: [=c2a,c4m].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[dix] :: [=c2a,c3,-m].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[dix] :: [=c2a,c3,-ms].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[dix] :: [=c2a,c2].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+es,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c2],dot)]
[dix] :: [=c2a,c2,-m1].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot)]
[dix] :: [=c2a,c3].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[dix] :: [c4m].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[dix] :: [c3,-m].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[dix] :: [c3,-ms].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[dix] :: [c2].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+es,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c2],dot)]
[dix] :: [c2,-m1].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot)]
[dix] :: [c3].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[deux] :: [c3e].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+k,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[deux] :: [c2,-e].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+k,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot)]
[deux] :: [c2,-es].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+k,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot)]
[deux] :: [c1,-e0].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+k,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot)]
[deux] :: [c2].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+hs,c2],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2],dot)]
[cinq] :: [c3e].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[cinq] :: [c2,-e].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot)]
[cinq] :: [c2,-es].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot)]
[cinq] :: [c1,-e0].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot)]
[cinq] :: [c2].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+hs,c2],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2],dot)]
[cent] :: [c3,-l].%[cent] :: [c3,-l,-s2s], [epsLi([=c3,+l,+s2s,c3,-l],dot)]
[cent] :: [c3,-l,-s2s].
[cent] :: [c43sl].%[cent] :: [c3,-l,-s2s], [epsLi([=c3,+l,+s2s,c3,-l],dot),epsLi([=c3,+l,c43sl],dot)]
[cent] :: [c3].%[cent] :: [c3,-l,-s2s], [epsLi([=c3,+s2s,c3],dot),epsLi([=c3,+s2,c3],dot),epsLi([=c3,+s2s,c3,-s2],dot),epsLi([=c3,+l,+s2s,c3,-l],dot),epsLi([=c3,+l,c3],dot)]
[cent] :: [=c4j,cfin].%[cent] :: [=c4j,c4], [epsLi([=c4,cfin],dot)]
[cent] :: [=c4j,c4].
[cent] :: [=c4m,=c3c,cfin].%[cent] :: [=c4m,=c3c,c4], [epsLi([=c4,cfin],dot)]
[cent] :: [=c4m,=c3c,c4].
[cents] :: [=c1,+c,cfin].%[cents] :: [=c1,+c,c4], [epsLi([=c4,cfin],dot)]
[cents] :: [=c1,+c,c4].
[cinq] :: [c1,-d].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+d,+c,+e0s,c1,-d],dot)]
[cinq] :: [c1,-d,-c,-e0s].
[cinq] :: [c3d].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c3d],dot)]
[cinq] :: [c1].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot)]
[cinq] :: [c4m].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[cinq] :: [c3].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c1,c3,-js],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[cinq] :: [c3,-m].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[cinq] :: [c3,-ms].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c3,-ms],dot)]
[cinq] :: [c3h].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[cinq] :: [c2,-h].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[cinq] :: [c2,-hs].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c2,-hs],dot)]
[cinq] :: [c4j].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[cinq] :: [c3,-j].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[cinq] :: [c3,-js].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c3,-js],dot)]
[cinq] :: [cfin].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[cinq] :: [c4].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+d,+c,+e0s,c1,-d],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,c4],dot)]
[deux] :: [c1,-k].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+k,+c,+e0s,c1,-k],dot)]
[deux] :: [c1,-k,-c,-e0s].
[deux] :: [c4k].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c4k],dot)]
[deux] :: [c1].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot)]
[deux] :: [c4m].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[deux] :: [c3].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c1,c3,-js],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[deux] :: [c3,-m].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[deux] :: [c3,-ms].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c3,-ms],dot)]
[deux] :: [c3h].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[deux] :: [c2,-h].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[deux] :: [c2,-hs].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c2,-hs],dot)]
[deux] :: [c4j].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[deux] :: [c3,-j].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[deux] :: [c3,-js].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c3,-js],dot)]
[deux] :: [cfin].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[deux] :: [c4].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+k,+c,+e0s,c1,-k],dot),epsLi([=c1,+k,c1],dot),epsLi([=c1,c4],dot)]
[dix] :: [c2,-s1].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot)]
[dix] :: [c2,-s1,-j1,-m1,-es].
[dix] :: [c4].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[dix] :: [cfin].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[dix] :: [=c2,+i,c31s].
[dix] :: [=c2,+i,c34s].
[dix] :: [=c2,+i,c37s].
[dix] :: [=c2a,c2,-s1].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot)]
[dix] :: [=c2a,c2,-s1,-j1,-m1,-es].
[dix] :: [=c2a,c4].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[dix] :: [=c2a,cfin].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[dix] :: [=c2a,=c39si,c33s].
[dix] :: [=c2a,=c39si,c36s].
[dix] :: [=c2a,=c39si,c39s].
[douze] :: [c2,-s1].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot)]
[douze] :: [c2,-s1,-j1,-h,-m1,-es].
[douze] :: [c4].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[douze] :: [cfin].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[huit] :: [c1,-c].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,+a,+e0s,c1,-c],dot)]
[huit] :: [c1,-c,-a,-e0s].
[huit] :: [c3c].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c3c],dot)]
[huit] :: [c1].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot)]
[huit] :: [c4m].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[huit] :: [c3].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c1,c3,-js],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[huit] :: [c3,-m].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[huit] :: [c3,-ms].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot)]
[huit] :: [c3h].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[huit] :: [c2,-h].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[huit] :: [c2,-hs].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot)]
[huit] :: [c4j].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[huit] :: [c3,-j].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[huit] :: [c3,-js].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot)]
[huit] :: [cfin].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[huit] :: [c4].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot)]
[neuf] :: [c1,-c].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,+a,+e0s,c1,-c],dot)]
[neuf] :: [c1,-c,-a,-e0s].
[neuf] :: [c3c].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c3c],dot)]
[neuf] :: [c1].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot)]
[neuf] :: [c4m].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[neuf] :: [c3].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c1,c3,-js],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[neuf] :: [c3,-m].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[neuf] :: [c3,-ms].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot)]
[neuf] :: [c3h].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[neuf] :: [c2,-h].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[neuf] :: [c2,-hs].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot)]
[neuf] :: [c4j].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[neuf] :: [c3,-j].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[neuf] :: [c3,-js].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot)]
[neuf] :: [cfin].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[neuf] :: [c4].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot)]
[onze] :: [c2,-s1].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,+j1,+f,+h,+m1s,c2,-s1],dot)]
[onze] :: [c2,-s1,-j1,-f,-h,-m1s].
[onze] :: [c4].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,+j1,+f,+h,+m1s,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[onze] :: [cfin].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,+j1,+f,+h,+m1s,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[quarante] :: [c3,-s2].%[quarante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[quarante] :: [c3,-s2,-j,-ms].
[quarante] :: [c4].%[quarante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[quarante] :: [c3].%[quarante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[quarante] :: [cfin].%[quarante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[quarante_] :: [=c3c,c3,-s2].%[quarante_] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[quarante_] :: [=c3c,c3,-s2,-j,-ms].
[quarante_] :: [=c3c,c4].%[quarante_] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[quarante_] :: [=c3c,c3].%[quarante_] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[quarante_] :: [=c3c,cfin].%[quarante_] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[quarante_et] :: [=c3b,c3,-s2].%[quarante_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[quarante_et] :: [=c3b,c3,-s2,-j,-ms].
[quarante_et] :: [=c3b,c4].%[quarante_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[quarante_et] :: [=c3b,c3].%[quarante_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[quarante_et] :: [=c3b,cfin].%[quarante_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[quatorze] :: [c2,-s1].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot)]
[quatorze] :: [c2,-s1,-j1,-h,-m1,-es].
[quatorze] :: [c4].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[quatorze] :: [cfin].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[quatre] :: [c1,-g].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+g,+c,+e0s,c1,-g],dot)]
[quatre] :: [c1,-g,-c,-e0s].
[quatre] :: [c3g].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c3g],dot)]
[quatre] :: [c1].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot)]
[quatre] :: [c4m].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[quatre] :: [c3].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c1,c3,-js],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[quatre] :: [c3,-m].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[quatre] :: [c3,-ms].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c3,-ms],dot)]
[quatre] :: [c3h].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[quatre] :: [c2,-h].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[quatre] :: [c2,-hs].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c2,-hs],dot)]
[quatre] :: [c4j].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[quatre] :: [c3,-j].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[quatre] :: [c3,-js].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c3,-js],dot)]
[quatre] :: [cfin].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[quatre] :: [c4].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+g,+c,+e0s,c1,-g],dot),epsLi([=c1,+g,c1],dot),epsLi([=c1,c4],dot)]
[quinze] :: [c2,-s1].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot)]
[quinze] :: [c2,-s1,-j1,-h,-m1,-es].
[quinze] :: [c4].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[quinze] :: [cfin].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[seize] :: [c2,-s1].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot)]
[seize] :: [c2,-s1,-j1,-m1,-es].
[seize] :: [c4].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[seize] :: [cfin].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,+j1,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[seize] :: [=c2,+i,c32s].
[seize] :: [=c2,+i,c35s].
[seize] :: [=c2,+i,c38s].
[sept] :: [c1,-c].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,+a,+e0s,c1,-c],dot)]
[sept] :: [c1,-c,-a,-e0s].
[sept] :: [c3c].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c3c],dot)]
[sept] :: [c1].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot)]
[sept] :: [c4m].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[sept] :: [c3].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+js,c3],dot),epsLi([=c1,c3,-js],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3],dot)]
[sept] :: [c3,-m].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[sept] :: [c3,-ms].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot)]
[sept] :: [c3h].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[sept] :: [c2,-h].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[sept] :: [c2,-hs].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot)]
[sept] :: [c4j].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[sept] :: [c3,-j].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[sept] :: [c3,-js].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot)]
[sept] :: [cfin].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[sept] :: [c4].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+a,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot)]
[six] :: [c1,-c].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+c,+e0s,c1,-c],dot)]
[six] :: [c1,-c,-e0s].
[six] :: [c3c].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c3c],dot)]
[six] :: [c1].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot)]
[six] :: [c4].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot)]
[six] :: [c3,-js].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot)]
[six] :: [c2,-hs].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot)]
[six] :: [c3,-ms].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot)]
[six] :: [cfin].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[six] :: [c3].%[six] :: [c1,-c,-e0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+ms,c3],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3],dot)]
[six] :: [c3,-j].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[six] :: [c2].%[six] :: [c1,-c,-e0s], [epsLi([=c2,+es,c2],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2],dot)]
[six] :: [c2,-h].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[six] :: [c3,-m].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[six] :: [c4j].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[six] :: [c3h].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[six] :: [c4m].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[soixante] :: [c3,-s2].%[soixante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[soixante] :: [c3,-s2,-j,-ms].
[soixante] :: [c4].%[soixante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[soixante] :: [c3].%[soixante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[soixante] :: [cfin].%[soixante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[soixante] :: [=c3e,c3,-s2].%[soixante] :: [=c3e,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[soixante] :: [=c3e,c3,-s2,-j,-ms].
[soixante] :: [=c3e,c4].%[soixante] :: [=c3e,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[soixante] :: [=c3e,c3].%[soixante] :: [=c3e,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[soixante] :: [=c3e,cfin].%[soixante] :: [=c3e,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[soixante_et] :: [=c3f,c3,-s2].%[soixante_et] :: [=c3f,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[soixante_et] :: [=c3f,c3,-s2,-j,-ms].
[soixante_et] :: [=c3f,c4].%[soixante_et] :: [=c3f,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[soixante_et] :: [=c3f,c3].%[soixante_et] :: [=c3f,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[soixante_et] :: [=c3f,cfin].%[soixante_et] :: [=c3f,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[treize] :: [c2,-s1].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot)]
[treize] :: [c2,-s1,-j1,-h,-m1,-es].
[treize] :: [c4].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[treize] :: [cfin].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,+j1,+h,+m1,+es,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[trente] :: [c3,-s2].%[trente] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[trente] :: [c3,-s2,-j,-ms].
[trente] :: [c4].%[trente] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[trente] :: [c3].%[trente] :: [c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[trente] :: [cfin].%[trente] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[trente] :: [=c3c,c3,-s2].%[trente] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[trente] :: [=c3c,c3,-s2,-j,-ms].
[trente] :: [=c3c,c4].%[trente] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[trente] :: [=c3c,c3].%[trente] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[trente] :: [=c3c,cfin].%[trente] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[trente_et] :: [=c3b,c3,-s2].%[trente_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[trente_et] :: [=c3b,c3,-s2,-j,-ms].
[trente_et] :: [=c3b,c4].%[trente_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[trente_et] :: [=c3b,c3].%[trente_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[trente_et] :: [=c3b,cfin].%[trente_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[trois] :: [c1,-c].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+c,+e0s,c1,-c],dot)]
[trois] :: [c1,-c,-e0s].
[trois] :: [c3c].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c3c],dot)]
[trois] :: [c1].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot)]
[trois] :: [c4].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot)]
[trois] :: [c3,-js].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot)]
[trois] :: [c2,-hs].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot)]
[trois] :: [c3,-ms].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot)]
[trois] :: [cfin].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[trois] :: [c3].%[trois] :: [c1,-c,-e0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+ms,c3],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3],dot)]
[trois] :: [c3,-j].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[trois] :: [c2].%[trois] :: [c1,-c,-e0s], [epsLi([=c2,+es,c2],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2],dot)]
[trois] :: [c2,-h].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[trois] :: [c3,-m].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[trois] :: [c4j].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[trois] :: [c3h].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[trois] :: [c4m].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+e0s,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[uante] :: [=c1,+d,c3,-s2].%[uante] :: [=c1,+d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[uante] :: [=c1,+d,c3,-s2,-j,-ms].
[uante] :: [=c1,+d,c4].%[uante] :: [=c1,+d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[uante] :: [=c1,+d,c3].%[uante] :: [=c1,+d,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[uante] :: [=c1,+d,cfin].%[uante] :: [=c1,+d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[uante] :: [=c3c,=c3d,c3,-s2].%[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms].
[uante] :: [=c3c,=c3d,c4].%[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[uante] :: [=c3c,=c3d,c3].%[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[uante] :: [=c3c,=c3d,cfin].%[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[uante_et] :: [=c3b,=c3d,c3,-s2].%[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms].
[uante_et] :: [=c3b,=c3d,c4].%[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[uante_et] :: [=c3b,=c3d,c3].%[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[uante_et] :: [=c3b,=c3d,cfin].%[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[un] :: [c1,-b].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+b,+f0s,c1,-b],dot)]
[un] :: [c1,-b,-f0s].
[un] :: [c3b].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c3b],dot)]
[un] :: [c1].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[un] :: [c4].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c4],dot)]
[un] :: [c3,-js].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3,-js],dot)]
[un] :: [c2,-hs].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-hs],dot)]
[un] :: [c3,-ms].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3,-ms],dot)]
[un] :: [cfin].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c4],dot),epsLi([=c4,cfin],dot)]
[un] :: [c3].%[un] :: [c1,-b,-f0s], [epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+ms,c3],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3],dot)]
[un] :: [c3,-j].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[un] :: [c2].%[un] :: [c1,-b,-f0s], [epsLi([=c2,+f,c2],dot),epsLi([=c2,+fs,c2,-f],dot),epsLi([=c2,+fs,c2],dot),epsLi([=c1,+f0,c2,-fs],dot),epsLi([=c1,+f0s,c1,-f0],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2],dot)]
[un] :: [c2,-h].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot)]
[un] :: [c3,-m].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[un] :: [c4j].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[un] :: [c3h].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-hs],dot),epsLi([=c2,+hs,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[un] :: [c4m].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+f0s,c1],dot),epsLi([=c1,+b,+f0s,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[vingt] :: [c2,-i].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,+s1,+j1,+m1s,c2,-i],dot)]
[vingt] :: [c2,-i,-s1,-j1,-m1s].
[vingt] :: [c39si].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,+s1,+j1,+m1s,c2,-i],dot),epsLi([=c2,+i,c39si],dot)]
[vingt] :: [=c3,+l,c41s].
[vingt] :: [=c3c,c3,-s2].%[vingt] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[vingt] :: [=c3c,c3,-s2,-j,-ms].
[vingt] :: [=c3c,c4].%[vingt] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[vingt] :: [=c3c,c3].%[vingt] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[vingt] :: [=c3c,cfin].%[vingt] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[vingt] :: [=c3c,=c43sl,c43s].
[vingt] :: [=c3h,=c3g,c3,-s2].%[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms].
[vingt] :: [=c3h,=c3g,c4].%[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[vingt] :: [=c3h,=c3g,c3].%[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[vingt] :: [=c3h,=c3g,cfin].%[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[vingt_et] :: [=c3b,c3,-s2].%[vingt_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[vingt_et] :: [=c3b,c3,-s2,-j,-ms].
[vingt_et] :: [=c3b,c4].%[vingt_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[vingt_et] :: [=c3b,c3].%[vingt_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[vingt_et] :: [=c3b,cfin].%[vingt_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[vingt_et] :: [=c3b,=c43sl,c42s].
[vingts] :: [=c1,+g,c3,-s2].%[vingts] :: [=c1,+g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot)]
[vingts] :: [=c1,+g,c3,-s2,-j,-ms].
[vingts] :: [=c1,+g,c4].%[vingts] :: [=c1,+g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[vingts] :: [=c1,+g,c3].%[vingts] :: [=c1,+g,c3,-s2,-j,-ms], [epsLi([=c3,+ms,c3],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c3],dot)]
[vingts] :: [=c1,+g,cfin].%[vingts] :: [=c1,+g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,+j,+ms,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[cent] :: [c4].%[cent] :: [c3,-l,-s2s], [epsLi([=c3,+l,c3],dot),epsLi([=c3,+s2s,c3,-s2],dot),epsLi([=c3,+s2,c4],dot)]
[cent] :: [c3,-s2].%[cent] :: [c3,-l,-s2s], [epsLi([=c3,+l,c3],dot),epsLi([=c3,+s2s,c3,-s2],dot)]
[cent] :: [cfin].%[cent] :: [c3,-l,-s2s], [epsLi([=c3,+l,c3],dot),epsLi([=c3,+s2s,c3,-s2],dot),epsLi([=c3,+s2,c4],dot),epsLi([=c4,cfin],dot)]
[cinq] :: [c3c].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c3c],dot)]
[cinq] :: [c1,-c].%[cinq] :: [c1,-d,-c,-e0s], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot)]
[deux] :: [c3c].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+k,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c3c],dot)]
[deux] :: [c1,-c].%[deux] :: [c1,-k,-c,-e0s], [epsLi([=c1,+k,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot)]
[dix] :: [c3,-js].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[dix] :: [c2,-j1].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot)]
[dix] :: [c3,-j].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[dix] :: [c4j].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[dix] :: [=c2a,c3,-js].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[dix] :: [=c2a,c2,-j1].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot)]
[dix] :: [=c2a,c3,-j].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[dix] :: [=c2a,c4j].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[douze] :: [c3,-js].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[douze] :: [c2,-j1].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot)]
[douze] :: [c3].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c3,+ms,c3],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3],dot)]
[douze] :: [c3,-j].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[douze] :: [c4j].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[huit] :: [c2a].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+a,c2a],dot)]
[huit] :: [c1,-a].%[huit] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot)]
[neuf] :: [c2a].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+a,c2a],dot)]
[neuf] :: [c1,-a].%[neuf] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot)]
[onze] :: [c3,-js].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+f,+h,+m1s,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[onze] :: [c2,-j1].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+f,+h,+m1s,c2,-j1],dot)]
[onze] :: [c3,-j].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+f,+h,+m1s,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[onze] :: [c4j].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+f,+h,+m1s,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[quarante] :: [c4j].%[quarante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[quarante] :: [c3,-j].%[quarante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[quarante_] :: [=c3c,c4j].%[quarante_] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[quarante_] :: [=c3c,c3,-j].%[quarante_] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[quarante_et] :: [=c3b,c4j].%[quarante_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[quarante_et] :: [=c3b,c3,-j].%[quarante_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[quatorze] :: [c3,-js].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[quatorze] :: [c2,-j1].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot)]
[quatorze] :: [c3].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c3,+ms,c3],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3],dot)]
[quatorze] :: [c3,-j].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[quatorze] :: [c4j].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[quatre] :: [c3c].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+g,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot),epsLi([=c1,+c,c3c],dot)]
[quatre] :: [c1,-c].%[quatre] :: [c1,-g,-c,-e0s], [epsLi([=c1,+g,c1],dot),epsLi([=c1,+c,+e0s,c1,-c],dot)]
[quinze] :: [c3,-js].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[quinze] :: [c2,-j1].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot)]
[quinze] :: [c3].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c3,+ms,c3],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3],dot)]
[quinze] :: [c3,-j].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[quinze] :: [c4j].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[seize] :: [c3,-js].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[seize] :: [c2,-j1].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot)]
[seize] :: [c3,-j].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[seize] :: [c4j].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[sept] :: [c2a].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot),epsLi([=c1,+a,c2a],dot)]
[sept] :: [c1,-a].%[sept] :: [c1,-c,-a,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+a,+e0s,c1,-a],dot)]
[six] :: [c2,-es].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot)]
[six] :: [c1,-e0].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot)]
[six] :: [c2,-e].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot)]
[six] :: [c3e].%[six] :: [c1,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[soixante] :: [c4j].%[soixante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[soixante] :: [c3,-j].%[soixante] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[soixante] :: [=c3e,c4j].%[soixante] :: [=c3e,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[soixante] :: [=c3e,c3,-j].%[soixante] :: [=c3e,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[soixante_et] :: [=c3f,c4j].%[soixante_et] :: [=c3f,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[soixante_et] :: [=c3f,c3,-j].%[soixante_et] :: [=c3f,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[treize] :: [c3,-js].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot)]
[treize] :: [c2,-j1].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot)]
[treize] :: [c3].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c3,+ms,c3],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c3,+j,c3],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3],dot)]
[treize] :: [c3,-j].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot)]
[treize] :: [c4j].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,+h,+m1,+es,c2,-j1],dot),epsLi([=c2,+j1,c3,-js],dot),epsLi([=c3,+js,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[trente] :: [c4j].%[trente] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[trente] :: [c3,-j].%[trente] :: [c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[trente] :: [=c3c,c4j].%[trente] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[trente] :: [=c3c,c3,-j].%[trente] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[trente_et] :: [=c3b,c4j].%[trente_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[trente_et] :: [=c3b,c3,-j].%[trente_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[trois] :: [c2,-es].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot)]
[trois] :: [c1,-e0].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot)]
[trois] :: [c2,-e].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot)]
[trois] :: [c3e].%[trois] :: [c1,-c,-e0s], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+e0s,c1,-e0],dot),epsLi([=c1,+e0,c2,-es],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[uante] :: [=c1,+d,c4j].%[uante] :: [=c1,+d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[uante] :: [=c1,+d,c3,-j].%[uante] :: [=c1,+d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[uante] :: [=c3c,=c3d,c4j].%[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[uante] :: [=c3c,=c3d,c3,-j].%[uante] :: [=c3c,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[uante_et] :: [=c3b,=c3d,c4j].%[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[uante_et] :: [=c3b,=c3d,c3,-j].%[uante_et] :: [=c3b,=c3d,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[un] :: [c2,-fs].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+f0s,c1,-f0],dot),epsLi([=c1,+f0,c2,-fs],dot)]
[un] :: [c1,-f0].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+f0s,c1,-f0],dot)]
[un] :: [c2,-f].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+f0s,c1,-f0],dot),epsLi([=c1,+f0,c2,-fs],dot),epsLi([=c2,+fs,c2,-f],dot)]
[un] :: [c3f].%[un] :: [c1,-b,-f0s], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+f0s,c1,-f0],dot),epsLi([=c1,+f0,c2,-fs],dot),epsLi([=c2,+fs,c2,-f],dot),epsLi([=c2,+f,c3f],dot)]
[vingt] :: [c4].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,+j1,+m1s,c2,-s1],dot),epsLi([=c2,+s1,c4],dot)]
[vingt] :: [c2,-s1].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,+j1,+m1s,c2,-s1],dot)]
[vingt] :: [cfin].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,+j1,+m1s,c2,-s1],dot),epsLi([=c2,+s1,c4],dot),epsLi([=c4,cfin],dot)]
[vingt] :: [=c3c,c4j].%[vingt] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[vingt] :: [=c3c,c3,-j].%[vingt] :: [=c3c,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[vingt] :: [=c3h,=c3g,c4j].%[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[vingt] :: [=c3h,=c3g,c3,-j].%[vingt] :: [=c3h,=c3g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[vingt_et] :: [=c3b,c4j].%[vingt_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[vingt_et] :: [=c3b,c3,-j].%[vingt_et] :: [=c3b,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[vingts] :: [=c1,+g,c4j].%[vingts] :: [=c1,+g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot),epsLi([=c3,+j,c4j],dot)]
[vingts] :: [=c1,+g,c3,-j].%[vingts] :: [=c1,+g,c3,-s2,-j,-ms], [epsLi([=c3,+s2,c3],dot),epsLi([=c3,+j,+ms,c3,-j],dot)]
[dix] :: [c3e].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[dix] :: [c2,-e].%[dix] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot)]
[dix] :: [=c2a,c3e].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[dix] :: [=c2a,c2,-e].%[dix] :: [=c2a,c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot)]
[douze] :: [c3,-ms].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[douze] :: [c2,-m1].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot)]
[douze] :: [c3,-m].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[douze] :: [c4m].%[douze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[onze] :: [c3h].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,c2],dot),epsLi([=c2,+h,+m1s,c2,-h],dot),epsLi([=c2,+h,c3h],dot)]
[onze] :: [c2,-h].%[onze] :: [c2,-s1,-j1,-f,-h,-m1s], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+f,c2],dot),epsLi([=c2,+h,+m1s,c2,-h],dot)]
[quatorze] :: [c3,-ms].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[quatorze] :: [c2,-m1].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot)]
[quatorze] :: [c3,-m].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[quatorze] :: [c4m].%[quatorze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[quinze] :: [c3,-ms].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[quinze] :: [c2,-m1].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot)]
[quinze] :: [c3,-m].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[quinze] :: [c4m].%[quinze] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[seize] :: [c3e].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[seize] :: [c2,-e].%[seize] :: [c2,-s1,-j1,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1,c2],dot),epsLi([=c2,+es,c2,-e],dot)]
[treize] :: [c3,-ms].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[treize] :: [c2,-m1].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot)]
[treize] :: [c3,-m].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[treize] :: [c4m].%[treize] :: [c2,-s1,-j1,-h,-m1,-es], [epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+h,c2],dot),epsLi([=c2,+m1,+es,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[vingt] :: [c3,-ms].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot)]
[vingt] :: [c2,-m1].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot)]
[vingt] :: [c3,-m].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot)]
[vingt] :: [c4m].%[vingt] :: [c2,-i,-s1,-j1,-m1s], [epsLi([=c2,+i,c2],dot),epsLi([=c2,+s1,c2],dot),epsLi([=c2,+j1,c2],dot),epsLi([=c2,+m1s,c2,-m1],dot),epsLi([=c2,+m1,c3,-ms],dot),epsLi([=c3,+ms,c3,-m],dot),epsLi([=c3,+m,c4m],dot)]
[] :: [=c31s,=c3g,c4m].
[] :: [=c31s,=c3g,c3,-m].
[] :: [=c41s,=c4k,cfin].
[] :: [=c41s,=c4k,c4].
[] :: [=c31s,=c3g,c3,-s2].
[] :: [=c31s,=c3g,c3,-s2,-j,-ms].
[] :: [=c31s,=c3g,c4].
[] :: [=c31s,=c3g,c3].
[] :: [=c31s,=c3g,cfin].
[] :: [=c31s,=c3g,c4j].
[] :: [=c31s,=c3g,c3,-j].
[] :: [=c41s,=c4k,c4].
[] :: [=c31s,=c3g,c3,-s2,-j,-ms].
