startCategory(cfin).
[drei]::[c1,-c,-b,-a].
[]::[=c3,cfin].
[zwei]::[c1,-b].
[vier]::[c1,-b,-a,-d].
[fünf]::[c1,-b,-a,-d].
[sechs]::[c1,-b].
[sieben]::[c1,-b].
[acht]::[c1,-b,-a,-d].
[neun]::[c1,-b,-a,-d].
[zehn]::[c2,-e,-s0].
[elf]::[c2,-e,-s0].
[zwölf]::[c2,-e,-s0].
[sechzehn]::[c2,-e,-s0].
[siebzehn]::[c2,-e,-s0].
[zwanzig]::[c2,-e,-s0].
[einundzwanzig]::[c2,-e,-s0].
[sechzig]::[c2,-e,-s0].
[einundsechzig]::[c2,-e,-s0].
[siebzig]::[c2,-e,-s0].
[einundsiebzig]::[c2,-e,-s0].
[]::[=c1,c2,-e].
[eins]::[c1].
[hundert]::[c3].
[hundert]::[=c3e,c3].
[]::[=c2,+e,c3e].
[hundert]::[=c1,+b,c3].
[hundert]::[=c3e,=c2b,c3].
[]::[=c1,+b,c3b].
[]::[=c2,+s0,c3].
[zehn]::[=c1,+a,c2,-s0].
[undzwanzig]::[=c1,+b,c2,-s0].
[ßig]::[=c1,+c,c2,-s0].
[einund]::[=c21s,c2,-s0].
[ßig]::[=c1,+c,c21s].
[und]::[=c22s,=c2b,c2,-s0].
[]::[=c1,+b,c2b].
[ßig]::[=c1,+c,c22s].
[zig]::[=c1,+d,c2,-s0].
[einund]::[=c23s,c2,-s0].
[zig]::[=c1,+d,c23s].
[und]::[=c24s,=c2b,c2,-s0].
[zig]::[=c1,+d,c24s].
[undsechzig]::[=c1,+b,c2,-s0].
[undsiebzig]::[=c1,+b,c2,-s0].
[]::[=c1,c3].
[]::[=c1,+d,c1].
[]::[=c1,+b,c1].
[]::[=c1,+c,c1].
[]::[=c2,+s0,c2].
[]::[=c1,+a,c1].
[]::[=c2,+e,c2].
[]::[=c2,+e,+s0,c2,-e].
[]::[=c1,+c,+b,+a,c1,-c].
[]::[=c1,+b,+a,+d,c1,-b].
[]::[=c1,+b,+a,c1,-b].
[]::[=c1,+a,+d,c1,-a].
