startCategory(cfin).
[eight] :: [c1,-b].
[ten] :: [c2,-s1].
[eleven] :: [c2,-s1].
[twelve] :: [c2,-s1].
[thirteen] :: [c2,-s1].
[fifteen] :: [c2,-s1].
[teen] :: [=c1,+a,c2,-s1].
[een] :: [=c1,+b,c2,-s1].
[twenty] :: [c2,-s1].
[twenty_] :: [=c1,c2,-s1].
[thirty] :: [c2,-s1].
[thirty_] :: [=c1,c2,-s1].
[forty] :: [c2,-s1].
[forty_] :: [=c1,c2,-s1].
[fifty] :: [c2,-s1].
[fifty_] :: [=c1,c2,-s1].
[ty] :: [=c1,+d,c2,-s1].
[ty_] :: [=c1,=c2d,c2,-s1].
[y] :: [=c1,+b,c2,-s1].
[y_] :: [=c1,=c2b,c2,-s1].
[one] :: [c1].
[two] :: [c1].
[three] :: [c1].
[four] :: [c1,-a].
[five] :: [c1].
[six] :: [c1,-a,-d].
[seven] :: [c1,-a,-d].
[nine] :: [c1,-a,-d].
[hundred] :: [=cnix,=c1,c3].
[hundred_and] :: [=c2,=c1,c3].
[] :: [=c3,cfin].
[] :: [=c1,+d,c2d].
[] :: [=c1,+b,c2b].
[] :: [=c1,c2].
[] :: [cnix].
[] :: [=c1,c3].
[] :: [=c2,+s1,c3].
[] :: [=c1,+a,c1].
[] :: [=c1,+d,c1].
[] :: [=c1,+b,c1].
[] :: [=c2,+s1,c2].
[] :: [=c1,+a,+d,c1,-a].
