startCategory(cfin).
[een] :: ([=c1,+b,cfin],abst(x,'0X+18'(x))).
[eight] :: ([c2b],8).
[eight] :: ([c1],8).
[eight] :: ([c1,-b],8).
[eight] :: ([c3e],8).
[eight] :: ([cfin],8).
[eleven] :: ([c3e],11).
[fifteen] :: ([c3e],15).
[fifty] :: ([c3e],50).
[fifty_] :: ([=c1,cfin],abst(x,'1X+50'(x))).
[five] :: ([c1],5).
[five] :: ([cfin],5).
[five] :: ([c3e],5).
[forty] :: ([c3e],40).
[forty_] :: ([=c1,cfin],abst(x,'1X+40'(x))).
[four] :: ([c1],4).
[four] :: ([c1,-a],4).
[four] :: ([c3e],4).
[four] :: ([cfin],4).
[hundred] :: ([=cnix,=c1,cfin],abst(x,abst(y,'1X+100Y'(x,y)))).
[hundred_and] :: ([=c3e,=c1,cfin],abst(x,abst(y,'1X+100Y'(x,y)))).
[nine] :: ([c1,-d],9).
[nine] :: ([c1,-d,-a],9).
[nine] :: ([c1],9).
[nine] :: ([c2d],9).
[nine] :: ([cfin],9).
[nine] :: ([c3e],9).
[one] :: ([c1],1).
[one] :: ([cfin],1).
[one] :: ([c3e],1).
[seven] :: ([c1,-d],7).
[seven] :: ([c1,-d,-a],7).
[seven] :: ([c1],7).
[seven] :: ([c2d],7).
[seven] :: ([cfin],7).
[seven] :: ([c3e],7).
[six] :: ([c1,-d],6).
[six] :: ([c1,-d,-a],6).
[six] :: ([c1],6).
[six] :: ([c2d],6).
[six] :: ([cfin],6).
[six] :: ([c3e],6).
[teen] :: ([=c1,+a,cfin],abst(x,'1X+10'(x))).
[ten] :: ([c3e],10).
[thirteen] :: ([c3e],13).
[thirty] :: ([c3e],30).
[thirty_] :: ([=c1,cfin],abst(x,'1X+30'(x))).
[three] :: ([c1],3).
[three] :: ([cfin],3).
[three] :: ([c3e],3).
[twelve] :: ([c3e],12).
[twenty] :: ([c3e],20).
[twenty_] :: ([=c1,cfin],abst(x,'1X+20'(x))).
[two] :: ([c1],2).
[two] :: ([cfin],2).
[two] :: ([c3e],2).
[ty] :: ([=c1,+d,cfin],abst(x,'10X'(x))).
[ty_] :: ([=c1,=c2d,cfin],abst(x,abst(y,'1X+10Y'(x,y)))).
[y] :: ([=c1,+b,cfin],abst(x,'0X+80'(x))).
[y_] :: ([=c1,=c2b,cfin],abst(x,abst(y,'1X+10Y'(x,y)))).
[eleven] :: ([cfin],11).
[fifteen] :: ([cfin],15).
[fifty] :: ([cfin],50).
[forty] :: ([cfin],40).
[ten] :: ([cfin],10).
[thirteen] :: ([cfin],13).
[thirty] :: ([cfin],30).
[twelve] :: ([cfin],12).
[twenty] :: ([cfin],20).
[] :: ([cnix],0).
