startCategory(cfin).
[acht] :: [c1,-b].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot)]
[acht] :: [c1,-b,-a,-d].
[acht] :: [c1].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[acht] :: [c3b].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c3b],dot)]
[acht] :: [c2b].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[acht] :: [cfin].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[acht] :: [c3].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot)]
[acht] :: [c3e].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[acht] :: [c2].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[acht] :: [c2,-e].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot)]
[drei] :: [c1,-c].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,+b,+a,c1,-c],dot)]
[drei] :: [c1,-c,-b,-a].
[drei] :: [c1].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot),epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot)]
[drei] :: [cfin].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[drei] :: [c3].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c3],dot)]
[drei] :: [c3e].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[drei] :: [c2].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[drei] :: [c2,-e].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+c,+b,+a,c1,-c],dot),epsLi([=c1,+c,c1],dot),epsLi([=c1,c2,-e],dot)]
[eins] :: [c2,-e].%[eins] :: [c1], [epsLi([=c1,c2,-e],dot)]
[eins] :: [c3].%[eins] :: [c1], [epsLi([=c1,c3],dot)]
[eins] :: [c1].
[eins] :: [cfin].%[eins] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[eins] :: [c3e].%[eins] :: [c1], [epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[eins] :: [c2].%[eins] :: [c1], [epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[einund] :: [=c21s,c3].%[einund] :: [=c21s,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[einund] :: [=c21s,c2].%[einund] :: [=c21s,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[einund] :: [=c21s,c2,-s0].
[einund] :: [=c21s,cfin].%[einund] :: [=c21s,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einund] :: [=c23s,c3].%[einund] :: [=c23s,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[einund] :: [=c23s,c2].%[einund] :: [=c23s,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[einund] :: [=c23s,c2,-s0].
[einund] :: [=c23s,cfin].%[einund] :: [=c23s,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einundsechzig] :: [c2,-e].%[einundsechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[einundsechzig] :: [c2,-e,-s0].
[einundsechzig] :: [c3e].%[einundsechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[einundsechzig] :: [c2].%[einundsechzig] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[einundsiebzig] :: [c2,-e].%[einundsiebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[einundsiebzig] :: [c2,-e,-s0].
[einundsiebzig] :: [c3e].%[einundsiebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[einundsiebzig] :: [c2].%[einundsiebzig] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[einundzwanzig] :: [c2,-e].%[einundzwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[einundzwanzig] :: [c2,-e,-s0].
[einundzwanzig] :: [c3e].%[einundzwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[einundzwanzig] :: [c2].%[einundzwanzig] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[elf] :: [c2,-e].%[elf] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[elf] :: [c2,-e,-s0].
[elf] :: [c3e].%[elf] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[elf] :: [c2].%[elf] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[fünf] :: [c1,-b].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot)]
[fünf] :: [c1,-b,-a,-d].
[fünf] :: [c1].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[fünf] :: [c3b].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c3b],dot)]
[fünf] :: [c2b].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[fünf] :: [cfin].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[fünf] :: [c3].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot)]
[fünf] :: [c3e].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[fünf] :: [c2].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[fünf] :: [c2,-e].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot)]
[hundert] :: [cfin].%[hundert] :: [c3], [epsLi([=c3,cfin],dot)]
[hundert] :: [c3].
[hundert] :: [=c1,+b,cfin].%[hundert] :: [=c1,+b,c3], [epsLi([=c3,cfin],dot)]
[hundert] :: [=c1,+b,c3].
[hundert] :: [=c3e,cfin].%[hundert] :: [=c3e,c3], [epsLi([=c3,cfin],dot)]
[hundert] :: [=c3e,c3].
[hundert] :: [=c3e,=c2b,cfin].%[hundert] :: [=c3e,=c2b,c3], [epsLi([=c3,cfin],dot)]
[hundert] :: [=c3e,=c2b,c3].
[neun] :: [c1,-b].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot)]
[neun] :: [c1,-b,-a,-d].
[neun] :: [c1].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[neun] :: [c3b].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c3b],dot)]
[neun] :: [c2b].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[neun] :: [cfin].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[neun] :: [c3].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot)]
[neun] :: [c3e].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[neun] :: [c2].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[neun] :: [c2,-e].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot)]
[sechs] :: [c1].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot)]
[sechs] :: [c3b].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c3b],dot)]
[sechs] :: [c2b].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c2b],dot)]
[sechs] :: [c1,-b].
[sechs] :: [c2,-e].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot)]
[sechs] :: [c3].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot)]
[sechs] :: [c3e].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sechs] :: [c2].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[sechs] :: [cfin].%[sechs] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[sechzehn] :: [c2,-e].%[sechzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[sechzehn] :: [c2,-e,-s0].
[sechzehn] :: [c3e].%[sechzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sechzehn] :: [c2].%[sechzehn] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[sechzig] :: [c2,-e].%[sechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[sechzig] :: [c2,-e,-s0].
[sechzig] :: [c3e].%[sechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sechzig] :: [c2].%[sechzig] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[sieben] :: [c1].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot)]
[sieben] :: [c3b].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c3b],dot)]
[sieben] :: [c2b].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c2b],dot)]
[sieben] :: [c1,-b].
[sieben] :: [c2,-e].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot)]
[sieben] :: [c3].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot)]
[sieben] :: [c3e].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[sieben] :: [c2].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[sieben] :: [cfin].%[sieben] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[siebzehn] :: [c2,-e].%[siebzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[siebzehn] :: [c2,-e,-s0].
[siebzehn] :: [c3e].%[siebzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[siebzehn] :: [c2].%[siebzehn] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[siebzig] :: [c2,-e].%[siebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[siebzig] :: [c2,-e,-s0].
[siebzig] :: [c3e].%[siebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[siebzig] :: [c2].%[siebzig] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[und] :: [=c22s,=c2b,c3].%[und] :: [=c22s,=c2b,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[und] :: [=c22s,=c2b,c2].%[und] :: [=c22s,=c2b,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[und] :: [=c22s,=c2b,c2,-s0].
[und] :: [=c22s,=c2b,cfin].%[und] :: [=c22s,=c2b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[und] :: [=c24s,=c2b,c3].%[und] :: [=c24s,=c2b,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[und] :: [=c24s,=c2b,c2].%[und] :: [=c24s,=c2b,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[und] :: [=c24s,=c2b,c2,-s0].
[und] :: [=c24s,=c2b,cfin].%[und] :: [=c24s,=c2b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[undsechzig] :: [=c1,+b,c3].%[undsechzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[undsechzig] :: [=c1,+b,c2].%[undsechzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[undsechzig] :: [=c1,+b,c2,-s0].
[undsechzig] :: [=c1,+b,cfin].%[undsechzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[undsiebzig] :: [=c1,+b,c3].%[undsiebzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[undsiebzig] :: [=c1,+b,c2].%[undsiebzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[undsiebzig] :: [=c1,+b,c2,-s0].
[undsiebzig] :: [=c1,+b,cfin].%[undsiebzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[undzwanzig] :: [=c1,+b,c3].%[undzwanzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[undzwanzig] :: [=c1,+b,c2].%[undzwanzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[undzwanzig] :: [=c1,+b,c2,-s0].
[undzwanzig] :: [=c1,+b,cfin].%[undzwanzig] :: [=c1,+b,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[vier] :: [c1,-b].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot)]
[vier] :: [c1,-b,-a,-d].
[vier] :: [c1].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+d,c1],dot),epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot)]
[vier] :: [c3b].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c3b],dot)]
[vier] :: [c2b].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[vier] :: [cfin].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[vier] :: [c3].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot)]
[vier] :: [c3e].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[vier] :: [c2].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[vier] :: [c2,-e].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+a,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot),epsLi([=c1,+d,c1],dot),epsLi([=c1,+b,+a,+d,c1,-b],dot),epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot)]
[zehn] :: [c2,-e].%[zehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[zehn] :: [c2,-e,-s0].
[zehn] :: [c3e].%[zehn] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[zehn] :: [c2].%[zehn] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[zehn] :: [=c1,+a,c3].%[zehn] :: [=c1,+a,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[zehn] :: [=c1,+a,c2].%[zehn] :: [=c1,+a,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[zehn] :: [=c1,+a,c2,-s0].
[zehn] :: [=c1,+a,cfin].%[zehn] :: [=c1,+a,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zig] :: [=c1,+d,c3].%[zig] :: [=c1,+d,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[zig] :: [=c1,+d,c2].%[zig] :: [=c1,+d,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[zig] :: [=c1,+d,c2,-s0].
[zig] :: [=c1,+d,cfin].%[zig] :: [=c1,+d,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zig] :: [=c1,+d,c23s].
[zig] :: [=c1,+d,c24s].
[zwanzig] :: [c2,-e].%[zwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[zwanzig] :: [c2,-e,-s0].
[zwanzig] :: [c3e].%[zwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[zwanzig] :: [c2].%[zwanzig] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[zwei] :: [c1].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot)]
[zwei] :: [c3b].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c3b],dot)]
[zwei] :: [c2b].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c2b],dot)]
[zwei] :: [c1,-b].
[zwei] :: [c2,-e].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot)]
[zwei] :: [c3].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot)]
[zwei] :: [c3e].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[zwei] :: [c2].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[zwei] :: [cfin].%[zwei] :: [c1,-b], [epsLi([=c1,+b,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cfin],dot)]
[zwölf] :: [c2,-e].%[zwölf] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot)]
[zwölf] :: [c2,-e,-s0].
[zwölf] :: [c3e].%[zwölf] :: [c2,-e,-s0], [epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c3e],dot)]
[zwölf] :: [c2].%[zwölf] :: [c2,-e,-s0], [epsLi([=c2,+s0,c2],dot),epsLi([=c2,+e,+s0,c2,-e],dot),epsLi([=c2,+e,c2],dot)]
[ßig] :: [=c1,+c,c3].%[ßig] :: [=c1,+c,c2,-s0], [epsLi([=c2,+s0,c3],dot)]
[ßig] :: [=c1,+c,c2].%[ßig] :: [=c1,+c,c2,-s0], [epsLi([=c2,+s0,c2],dot)]
[ßig] :: [=c1,+c,c2,-s0].
[ßig] :: [=c1,+c,cfin].%[ßig] :: [=c1,+c,c2,-s0], [epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[ßig] :: [=c1,+c,c21s].
[ßig] :: [=c1,+c,c22s].
[acht] :: [c1,-a].%[acht] :: [c1,-b,-a,-d], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot)]
[drei] :: [c3b].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot),epsLi([=c1,+b,c3b],dot)]
[drei] :: [c2b].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot),epsLi([=c1,+b,c2b],dot)]
[drei] :: [c1,-b].%[drei] :: [c1,-c,-b,-a], [epsLi([=c1,+c,c1],dot),epsLi([=c1,+b,+a,c1,-b],dot)]
[einundsechzig] :: [cfin].%[einundsechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einundsechzig] :: [c3].%[einundsechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[einundsiebzig] :: [cfin].%[einundsiebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einundsiebzig] :: [c3].%[einundsiebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[einundzwanzig] :: [cfin].%[einundzwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[einundzwanzig] :: [c3].%[einundzwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[elf] :: [cfin].%[elf] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[elf] :: [c3].%[elf] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[fünf] :: [c1,-a].%[fünf] :: [c1,-b,-a,-d], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot)]
[neun] :: [c1,-a].%[neun] :: [c1,-b,-a,-d], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot)]
[sechzehn] :: [cfin].%[sechzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[sechzehn] :: [c3].%[sechzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[sechzig] :: [cfin].%[sechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[sechzig] :: [c3].%[sechzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[siebzehn] :: [cfin].%[siebzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[siebzehn] :: [c3].%[siebzehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[siebzig] :: [cfin].%[siebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[siebzig] :: [c3].%[siebzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[vier] :: [c1,-a].%[vier] :: [c1,-b,-a,-d], [epsLi([=c1,+b,c1],dot),epsLi([=c1,+a,+d,c1,-a],dot)]
[zehn] :: [cfin].%[zehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zehn] :: [c3].%[zehn] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[zwanzig] :: [cfin].%[zwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zwanzig] :: [c3].%[zwanzig] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
[zwölf] :: [cfin].%[zwölf] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot),epsLi([=c3,cfin],dot)]
[zwölf] :: [c3].%[zwölf] :: [c2,-e,-s0], [epsLi([=c2,+e,c2],dot),epsLi([=c2,+s0,c3],dot)]
