parse_tree_case(1, [one], ok, [li([one],[cfin])]).
parse_tree_case(2, [two], ok, [li([two],[cfin])]).
parse_tree_case(3, [three], ok, [li([three],[cfin])]).
parse_tree_case(4, [four], ok, [li([four],[cfin])]).
parse_tree_case(5, [five], ok, [li([five],[cfin])]).
parse_tree_case(6, [six], ok, [li([six],[cfin])]).
parse_tree_case(7, [seven], ok, [li([seven],[cfin])]).
parse_tree_case(8, [eight], ok, [li([eight],[cfin])]).
parse_tree_case(9, [nine], ok, [li([nine],[cfin])]).
parse_tree_case(10, [ten], ok, [li([ten],[cfin])]).
parse_tree_case(11, [eleven], ok, [li([eleven],[cfin])]).
parse_tree_case(12, [twelve], ok, [li([twelve],[cfin])]).
parse_tree_case(13, [thirteen], ok, [li([thirteen],[cfin])]).
parse_tree_case(15, [fifteen], ok, [li([fifteen],[cfin])]).
parse_tree_case(18, [], parse_skipped_empty_tokens, none).
parse_tree_case(20, [twenty], ok, [li([twenty],[cfin])]).
parse_tree_case(30, [thirty], ok, [li([thirty],[cfin])]).
parse_tree_case(50, [fifty], ok, [li([fifty],[cfin])]).
parse_tree_case('1X+10'(4), [four,teen], ok, [tree(_107876,empty,tree(_107518,li([teen],[=c1,+a,cfin]),li([four],[c1,-a])))]).
parse_tree_case('1X+10'(6), [six,teen], parse_fail, none).
parse_tree_case('1X+10'(7), [seven,teen], parse_fail, none).
parse_tree_case('0X+18'(8), [eight,een], ok, [tree(_107876,empty,tree(_107518,li([een],[=c1,+b,cfin]),li([eight],[c1,-b])))]).
parse_tree_case('1X+10'(9), [nine,teen], parse_fail, none).
parse_tree_case('1X+20'(1), [twenty_,one], ok, [tree(_107450,li([twenty_],[=c1,cfin]),li([one],[c1]))]).
parse_tree_case('1X+20'(2), [twenty_,two], ok, [tree(_107450,li([twenty_],[=c1,cfin]),li([two],[c1]))]).
parse_tree_case('1X+20'(3), [twenty_,three], ok, [tree(_107450,li([twenty_],[=c1,cfin]),li([three],[c1]))]).
parse_tree_case('1X+20'(4), [twenty_,four], ok, [tree(_107456,li([twenty_],[=c1,cfin]),li([four],[c1]))]).
parse_tree_case('1X+20'(5), [twenty_,five], ok, [tree(_107450,li([twenty_],[=c1,cfin]),li([five],[c1]))]).
parse_tree_case('1X+20'(6), [twenty_,six], ok, [tree(_107456,li([twenty_],[=c1,cfin]),li([six],[c1]))]).
parse_tree_case('1X+20'(7), [twenty_,seven], ok, [tree(_107456,li([twenty_],[=c1,cfin]),li([seven],[c1]))]).
parse_tree_case('1X+20'(8), [twenty_,eight], ok, [tree(_107456,li([twenty_],[=c1,cfin]),li([eight],[c1]))]).
parse_tree_case('1X+20'(9), [twenty_,nine], ok, [tree(_107456,li([twenty_],[=c1,cfin]),li([nine],[c1]))]).
parse_tree_case('1X+30'(1), [thirty_,one], ok, [tree(_107450,li([thirty_],[=c1,cfin]),li([one],[c1]))]).
parse_tree_case('1X+30'(2), [thirty_,two], ok, [tree(_107450,li([thirty_],[=c1,cfin]),li([two],[c1]))]).
parse_tree_case('1X+30'(3), [thirty_,three], ok, [tree(_107450,li([thirty_],[=c1,cfin]),li([three],[c1]))]).
parse_tree_case('1X+30'(4), [thirty_,four], ok, [tree(_107456,li([thirty_],[=c1,cfin]),li([four],[c1]))]).
parse_tree_case('1X+30'(5), [thirty_,five], ok, [tree(_107450,li([thirty_],[=c1,cfin]),li([five],[c1]))]).
parse_tree_case('1X+30'(6), [thirty_,six], ok, [tree(_107456,li([thirty_],[=c1,cfin]),li([six],[c1]))]).
parse_tree_case('1X+30'(7), [thirty_,seven], ok, [tree(_107456,li([thirty_],[=c1,cfin]),li([seven],[c1]))]).
parse_tree_case('1X+30'(8), [thirty_,eight], ok, [tree(_107456,li([thirty_],[=c1,cfin]),li([eight],[c1]))]).
parse_tree_case('1X+30'(9), [thirty_,nine], ok, [tree(_107456,li([thirty_],[=c1,cfin]),li([nine],[c1]))]).
parse_tree_case('1X+50'(1), [fifty_,one], ok, [tree(_107450,li([fifty_],[=c1,cfin]),li([one],[c1]))]).
parse_tree_case('1X+50'(2), [fifty_,two], ok, [tree(_107450,li([fifty_],[=c1,cfin]),li([two],[c1]))]).
parse_tree_case('1X+50'(3), [fifty_,three], ok, [tree(_107450,li([fifty_],[=c1,cfin]),li([three],[c1]))]).
parse_tree_case('1X+50'(4), [fifty_,four], ok, [tree(_107456,li([fifty_],[=c1,cfin]),li([four],[c1]))]).
parse_tree_case('1X+50'(5), [fifty_,five], ok, [tree(_107450,li([fifty_],[=c1,cfin]),li([five],[c1]))]).
parse_tree_case('1X+50'(6), [fifty_,six], ok, [tree(_107456,li([fifty_],[=c1,cfin]),li([six],[c1]))]).
parse_tree_case('1X+50'(7), [fifty_,seven], ok, [tree(_107456,li([fifty_],[=c1,cfin]),li([seven],[c1]))]).
parse_tree_case('1X+50'(8), [fifty_,eight], ok, [tree(_107456,li([fifty_],[=c1,cfin]),li([eight],[c1]))]).
parse_tree_case('1X+50'(9), [fifty_,nine], ok, [tree(_107456,li([fifty_],[=c1,cfin]),li([nine],[c1]))]).
parse_tree_case('1X+40'(4), [], parse_skipped_empty_tokens, none).
parse_tree_case('1X+60'(4), [], parse_skipped_empty_tokens, none).
parse_tree_case('1X+70'(4), [], parse_skipped_empty_tokens, none).
parse_tree_case('1X+80'(4), [], parse_skipped_empty_tokens, none).
parse_tree_case('1X+90'(4), [], parse_skipped_empty_tokens, none).
