bidir_case(1, ok, [one], [one], [one], ok, 1).
bidir_case(2, ok, [two], [two], [two], ok, 2).
bidir_case(3, ok, [three], [three], [three], ok, 3).
bidir_case(4, ok, [four], [four], [four], ok, 4).
bidir_case(5, ok, [five], [five], [five], ok, 5).
bidir_case(6, ok, [six], [six], [six], ok, 6).
bidir_case(7, ok, [seven], [seven], [seven], ok, 7).
bidir_case(8, ok, [eight], [eight], [eight], ok, 8).
bidir_case(9, ok, [nine], [nine], [nine], ok, 9).
bidir_case(10, ok, [ten], [ten], [ten], ok, 10).
bidir_case(11, ok, [eleven], [eleven], [eleven], ok, 11).
bidir_case(12, ok, [twelve], [twelve], [twelve], ok, 12).
bidir_case(13, ok, [thirteen], [thirteen], [thirteen], ok, 13).
bidir_case(15, ok, [fifteen], [fifteen], [fifteen], ok, 15).
bidir_case(18, gen_empty_yield, [], [], [], parse_skipped_empty_tokens, none).
bidir_case(20, ok, [twenty], [twenty], [twenty], ok, 20).
bidir_case(30, ok, [thirty], [thirty], [thirty], ok, 30).
bidir_case(50, ok, [fifty], [fifty], [fifty], ok, 50).
bidir_case('1X+10'(4), ok, [four,teen], [four,teen], [four,teen], ok, '1X+10'(4)).
bidir_case('1X+10'(6), ok, [six,teen], [six,teen], [six,teen], parse_fail, none).
bidir_case('1X+10'(7), ok, [seven,teen], [seven,teen], [seven,teen], parse_fail, none).
bidir_case('0X+18'(8), ok, [eight,een], [eight,een], [eight,een], ok, '0X+18'(8)).
bidir_case('1X+10'(9), ok, [nine,teen], [nine,teen], [nine,teen], parse_fail, none).
bidir_case('1X+20'(1), ok, [twenty,one], [twenty,one], [twenty,one], parse_fail, none).
bidir_case('1X+20'(2), ok, [twenty,two], [twenty,two], [twenty,two], parse_fail, none).
bidir_case('1X+20'(3), ok, [twenty,three], [twenty,three], [twenty,three], parse_fail, none).
bidir_case('1X+20'(4), ok, [twenty], [twenty], [twenty], ok, 20).
bidir_case('1X+20'(5), ok, [twenty,five], [twenty,five], [twenty,five], parse_fail, none).
bidir_case('1X+20'(6), ok, [twenty], [twenty], [twenty], ok, 20).
bidir_case('1X+20'(7), ok, [twenty], [twenty], [twenty], ok, 20).
bidir_case('1X+20'(8), ok, [twenty], [twenty], [twenty], ok, 20).
bidir_case('1X+20'(9), ok, [twenty], [twenty], [twenty], ok, 20).
bidir_case('1X+30'(1), ok, [thirty,one], [thirty,one], [thirty,one], parse_fail, none).
bidir_case('1X+30'(2), ok, [thirty,two], [thirty,two], [thirty,two], parse_fail, none).
bidir_case('1X+30'(3), ok, [thirty,three], [thirty,three], [thirty,three], parse_fail, none).
bidir_case('1X+30'(4), ok, [thirty], [thirty], [thirty], ok, 30).
bidir_case('1X+30'(5), ok, [thirty,five], [thirty,five], [thirty,five], parse_fail, none).
bidir_case('1X+30'(6), ok, [thirty], [thirty], [thirty], ok, 30).
bidir_case('1X+30'(7), ok, [thirty], [thirty], [thirty], ok, 30).
bidir_case('1X+30'(8), ok, [thirty], [thirty], [thirty], ok, 30).
bidir_case('1X+30'(9), ok, [thirty], [thirty], [thirty], ok, 30).
bidir_case('1X+50'(1), ok, [fifty,one], [fifty,one], [fifty,one], parse_fail, none).
bidir_case('1X+50'(2), ok, [fifty,two], [fifty,two], [fifty,two], parse_fail, none).
bidir_case('1X+50'(3), ok, [fifty,three], [fifty,three], [fifty,three], parse_fail, none).
bidir_case('1X+50'(4), ok, [fifty], [fifty], [fifty], ok, 50).
bidir_case('1X+50'(5), ok, [fifty,five], [fifty,five], [fifty,five], parse_fail, none).
bidir_case('1X+50'(6), ok, [fifty], [fifty], [fifty], ok, 50).
bidir_case('1X+50'(7), ok, [fifty], [fifty], [fifty], ok, 50).
bidir_case('1X+50'(8), ok, [fifty], [fifty], [fifty], ok, 50).
bidir_case('1X+50'(9), ok, [fifty], [fifty], [fifty], ok, 50).
bidir_case('1X+40'(4), gen_empty_yield, [], [], [], parse_skipped_empty_tokens, none).
bidir_case('1X+60'(4), gen_empty_yield, [], [], [], parse_skipped_empty_tokens, none).
bidir_case('1X+70'(4), gen_empty_yield, [], [], [], parse_skipped_empty_tokens, none).
bidir_case('1X+80'(4), gen_empty_yield, [], [], [], parse_skipped_empty_tokens, none).
bidir_case('1X+90'(4), gen_empty_yield, [], [], [], parse_skipped_empty_tokens, none).
