gen_case(1, ok, [eins], eins).
gen_case(3, ok, [drei], drei).
gen_case(10, ok, [zehn], zehn).
gen_case(11, ok, [elf], elf).
gen_case(12, ok, [zwölf], zwölf).
gen_case(16, ok, [sechzehn], sechzehn).
gen_case(17, ok, [siebzehn], siebzehn).
gen_case(20, ok, [zwanzig], zwanzig).
gen_case(21, ok, [einundzwanzig], einundzwanzig).
gen_case(60, ok, [sechzig], sechzig).
gen_case(61, ok, [einundsechzig], einundsechzig).
gen_case(70, ok, [siebzig], siebzig).
gen_case(71, ok, [einundsiebzig], einundsiebzig).
gen_case(100, ok, [hundert], hundert).
gen_case('1X+10'(3), ok, [zehn], zehn).
gen_case('1X+20'(2), ok, [zwei,undzwanzig], zweiundzwanzig).
gen_case('0X+30'(3), ok, [ßig], ßig).
gen_case('10X'(4), ok, [zig], zig).
gen_case('1X+31'(1), error(time_limit_exceeded), [], '').
