reverse_case([one], ok, 1, ok, [one], [one]).
reverse_case([two], ok, 2, ok, [two], [two]).
reverse_case([three], ok, 3, ok, [three], [three]).
reverse_case([four], ok, 4, ok, [four], [four]).
reverse_case([five], ok, 5, ok, [five], [five]).
reverse_case([six], ok, 6, ok, [six], [six]).
reverse_case([seven], ok, 7, ok, [seven], [seven]).
reverse_case([eight], ok, 8, ok, [eight], [eight]).
reverse_case([nine], ok, 9, ok, [nine], [nine]).
reverse_case([ten], ok, 10, ok, [ten], [ten]).
reverse_case([eleven], ok, 11, ok, [eleven], [eleven]).
reverse_case([twelve], ok, 12, ok, [twelve], [twelve]).
reverse_case([thirteen], ok, 13, ok, [thirteen], [thirteen]).
reverse_case([fifteen], ok, 15, ok, [fifteen], [fifteen]).
reverse_case([four,teen], ok, '1X+10'(4), ok, [four,teen], [four,teen]).
reverse_case([eight,een], ok, '0X+18'(8), ok, [eight,een], [eight,een]).
reverse_case([twenty], ok, 20, ok, [twenty], [twenty]).
reverse_case([thirty], ok, 30, ok, [thirty], [thirty]).
reverse_case([fifty], ok, 50, ok, [fifty], [fifty]).
reverse_case([twenty_,one], ok, '1X+20'(1), ok, [twenty,one], [twenty_,one]).
reverse_case([twenty_,two], ok, '1X+20'(2), ok, [twenty,two], [twenty_,two]).
reverse_case([twenty_,three], ok, '1X+20'(3), ok, [twenty,three], [twenty_,three]).
reverse_case([twenty_,four], ok, '1X+20'(4), ok, [twenty], [twenty]).
reverse_case([twenty_,five], ok, '1X+20'(5), ok, [twenty,five], [twenty_,five]).
reverse_case([twenty_,six], ok, '1X+20'(6), ok, [twenty], [twenty]).
reverse_case([twenty_,seven], ok, '1X+20'(7), ok, [twenty], [twenty]).
reverse_case([twenty_,eight], ok, '1X+20'(8), ok, [twenty], [twenty]).
reverse_case([twenty_,nine], ok, '1X+20'(9), ok, [twenty], [twenty]).
reverse_case([thirty_,one], ok, '1X+30'(1), ok, [thirty,one], [thirty_,one]).
reverse_case([thirty_,two], ok, '1X+30'(2), ok, [thirty,two], [thirty_,two]).
reverse_case([thirty_,three], ok, '1X+30'(3), ok, [thirty,three], [thirty_,three]).
reverse_case([thirty_,four], ok, '1X+30'(4), ok, [thirty], [thirty]).
reverse_case([thirty_,five], ok, '1X+30'(5), ok, [thirty,five], [thirty_,five]).
reverse_case([thirty_,six], ok, '1X+30'(6), ok, [thirty], [thirty]).
reverse_case([thirty_,seven], ok, '1X+30'(7), ok, [thirty], [thirty]).
reverse_case([thirty_,eight], ok, '1X+30'(8), ok, [thirty], [thirty]).
reverse_case([thirty_,nine], ok, '1X+30'(9), ok, [thirty], [thirty]).
reverse_case([fifty_,one], ok, '1X+50'(1), ok, [fifty,one], [fifty_,one]).
reverse_case([fifty_,two], ok, '1X+50'(2), ok, [fifty,two], [fifty_,two]).
reverse_case([fifty_,three], ok, '1X+50'(3), ok, [fifty,three], [fifty_,three]).
reverse_case([fifty_,four], ok, '1X+50'(4), ok, [fifty], [fifty]).
reverse_case([fifty_,five], ok, '1X+50'(5), ok, [fifty,five], [fifty_,five]).
reverse_case([fifty_,six], ok, '1X+50'(6), ok, [fifty], [fifty]).
reverse_case([fifty_,seven], ok, '1X+50'(7), ok, [fifty], [fifty]).
reverse_case([fifty_,eight], ok, '1X+50'(8), ok, [fifty], [fifty]).
reverse_case([fifty_,nine], ok, '1X+50'(9), ok, [fifty], [fifty]).
