reverse_parse_case([one], ok, 1).
reverse_parse_case([two], ok, 2).
reverse_parse_case([three], ok, 3).
reverse_parse_case([four], ok, 4).
reverse_parse_case([five], ok, 5).
reverse_parse_case([six], ok, 6).
reverse_parse_case([seven], ok, 7).
reverse_parse_case([eight], ok, 8).
reverse_parse_case([nine], ok, 9).
reverse_parse_case([ten], ok, 10).
reverse_parse_case([eleven], ok, 11).
reverse_parse_case([twelve], ok, 12).
reverse_parse_case([thirteen], ok, 13).
reverse_parse_case([fifteen], ok, 15).
reverse_parse_case([four,teen], ok, '1X+10'(4)).
reverse_parse_case([eight,een], ok, '0X+18'(8)).
reverse_parse_case([twenty], ok, 20).
reverse_parse_case([thirty], ok, 30).
reverse_parse_case([fifty], ok, 50).
reverse_parse_case([twenty_,one], ok, '1X+20'(1)).
reverse_parse_case([twenty_,two], ok, '1X+20'(2)).
reverse_parse_case([twenty_,three], ok, '1X+20'(3)).
reverse_parse_case([twenty_,four], ok, '1X+20'(4)).
reverse_parse_case([twenty_,five], ok, '1X+20'(5)).
reverse_parse_case([twenty_,six], ok, '1X+20'(6)).
reverse_parse_case([twenty_,seven], ok, '1X+20'(7)).
reverse_parse_case([twenty_,eight], ok, '1X+20'(8)).
reverse_parse_case([twenty_,nine], ok, '1X+20'(9)).
reverse_parse_case([thirty_,one], ok, '1X+30'(1)).
reverse_parse_case([thirty_,two], ok, '1X+30'(2)).
reverse_parse_case([thirty_,three], ok, '1X+30'(3)).
reverse_parse_case([thirty_,four], ok, '1X+30'(4)).
reverse_parse_case([thirty_,five], ok, '1X+30'(5)).
reverse_parse_case([thirty_,six], ok, '1X+30'(6)).
reverse_parse_case([thirty_,seven], ok, '1X+30'(7)).
reverse_parse_case([thirty_,eight], ok, '1X+30'(8)).
reverse_parse_case([thirty_,nine], ok, '1X+30'(9)).
reverse_parse_case([fifty_,one], ok, '1X+50'(1)).
reverse_parse_case([fifty_,two], ok, '1X+50'(2)).
reverse_parse_case([fifty_,three], ok, '1X+50'(3)).
reverse_parse_case([fifty_,four], ok, '1X+50'(4)).
reverse_parse_case([fifty_,five], ok, '1X+50'(5)).
reverse_parse_case([fifty_,six], ok, '1X+50'(6)).
reverse_parse_case([fifty_,seven], ok, '1X+50'(7)).
reverse_parse_case([fifty_,eight], ok, '1X+50'(8)).
reverse_parse_case([fifty_,nine], ok, '1X+50'(9)).
